# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rest_error.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='rest_error.proto',
  package='gazebo.msgs',
  syntax='proto2',
  options=None,
  serialized_pb=_b('\n\x10rest_error.proto\x12\x0bgazebo.msgs\"&\n\tRestError\x12\x0c\n\x04type\x18\x01 \x02(\t\x12\x0b\n\x03msg\x18\x02 \x01(\t')
)




_RESTERROR = _descriptor.Descriptor(
  name='RestError',
  full_name='gazebo.msgs.RestError',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='type', full_name='gazebo.msgs.RestError.type', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='msg', full_name='gazebo.msgs.RestError.msg', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=33,
  serialized_end=71,
)

DESCRIPTOR.message_types_by_name['RestError'] = _RESTERROR
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

RestError = _reflection.GeneratedProtocolMessageType('RestError', (_message.Message,), dict(
  DESCRIPTOR = _RESTERROR,
  __module__ = 'rest_error_pb2'
  # @@protoc_insertion_point(class_scope:gazebo.msgs.RestError)
  ))
_sym_db.RegisterMessage(RestError)


# @@protoc_insertion_point(module_scope)
